nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin:
           - "http://localhost:5173"
            - "http://127.0.0.1:5173"
    allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
    allow_headers: ["Content-Type", "Authorization", "X-Requested-With"]
    expose_headers: ["Link"]
    max_age: 3600
    allow_credentials: false

  paths:
    "^/batipilot_api/api/":
      allow_origin:
        - "http://localhost:5173"
        - "http://127.0.0.1:5173"
      allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
      allow_headers: ["Content-Type", "Authorization", "X-Requested-With"]
      max_age: 3600